// pokemons
export const FETCH_POKEMONS = 'FETCH_POKEMONS'
export const REQUEST_POKEMONS = 'REQUEST_POKEMONS'
export const RECEIVE_POKEMONS = 'RECEIVE_POKEMONS'
export const SELECT_POKEMON = 'SELECT_POKEMON'
export const REQUEST_POKEMON_DETAILS = 'REQUEST_POKEMON_DETAILS'
export const RECEIVE_POKEMON_DETAILS = 'RECEIVE_POKEMON_DETAILS'
export const RECEIVE_POKEMON_EVOLUTIONS = 'RECEIVE_POKEMON_EVOLUTIONS'
// search
export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER'
export const CLEAR_SEARCH_FILTER = 'CLEAR_SEARCH_FILTER'
// favorites
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE'
// caught
export const TOGGLE_CAUGHT = 'TOGGLE_CAUGHT'
